ServiceHost = "0.0.0.0"  # 0.0.0.0 для доступа из сети, localhost - только локально
ServicePort = 8080

# JWT настройки
jwt_secret = "test"
jwt_expire = "24h"
jwt_algorithm = "HS256"

# Redis настройки
redis_host = "localhost"
redis_port = 6379
redis_password = "password"
redis_user = ""
redis_dial_timeout = "10s"
redis_read_timeout = "10s"